### ISSUE TITLE
How about working together 

### ISSUE THREAD

**Issue by Janglee123** [EveReader/EveReader#2]
Hi, I am Meru. Found this repo while randomly browsing. I am currently working on [eplee](https://github.com/Janglee123/eplee). Eplee is the same app Like EveReader. It is an electron-based epub reader uses the same library, too. I like that someone is also working on the same idea.

if you want to work together we may talk here.

Thank you

**Comment by xianmin** [comment]
@Janglee123 Hi Meru! Nice to know you. I am Xianmin.

Thanks let me know your great work! I'm glad to work together on the same idea. I need some time to get familiar with the progress of your project. And I am too busy recently. Sorry for reply too late. I am very interested in your work.

Sincerely!

**Comment by Janglee123** [comment]
Thank you.
